# Generated by Django 4.2.6 on 2023-10-28 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentapp', '0002_remove_student_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='conf_password',
            field=models.CharField(default='', max_length=16),
        ),
        migrations.AlterField(
            model_name='student',
            name='password',
            field=models.CharField(max_length=16),
        ),
    ]
