# Generated by Django 4.2.6 on 2023-10-28 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentapp', '0003_student_conf_password_alter_student_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='profile_pic',
            field=models.CharField(default='', max_length=200),
        ),
    ]
