# Generated by Django 4.2.6 on 2023-11-05 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studentapp', '0007_alter_profile_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='contact',
        ),
    ]
