# Generated by Django 4.2.6 on 2023-11-05 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentapp', '0008_remove_profile_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='contact',
            field=models.CharField(default='98', max_length=14),
        ),
    ]
